db = db.getSiblingDB('api')
db.txs.ensureIndex({"tx.hash":1},{ unique: true })
db.txs.ensureIndex({"blocknumber":1})
db.blocks.ensureIndex({"number":1},{ unique: true })
db.blocks.ensureIndex({"hash":1},{ unique: true })
db.accounts.ensureIndex({"accountInfo.gasinfo.pledgedinfo.pledger":1})
db.accounts.ensureIndex({"pubkeys":1})
db.accounts.ensureIndex({"name":1},{ unique: true })
db.accountTx.ensureIndex({"name":1, "time":-1, "tokens":1})
db.accountTx.ensureIndex({"name":1, "_id":1})
db.contracts.ensureIndex({"id":1},{ unique: true })
db.contractTx.ensureIndex({"id":1, "time":-1})
db.contractTx.ensureIndex({"id":1, "_id":1})
db.candidate.ensureIndex({"name":1},{unique: true})
